### ISSUE TITLE
Not showing badges in sidebar

### ISSUE THREAD

**Issue by equinusocio** [Sidnioulz/storybook-addon-tag-badges#15]
## Story
```tsx
import type { Meta, StoryObj } from '@storybook/react';

import { IconButton } from '@/components';

import { Badge } from './badge';

const meta = {
  title: 'Badges/Badge',
  component: Badge,
  args: {
    showBadge: true,
  },
  tags: ['code-only'],
  render: args => (
    <Badge {...args}>
      <IconButton
        aria-label="Enable or disable notifications"
        icon="bell"
        dimension="big"
      />
    </Badge>
  ),
} satisfies Meta<typeof Badge>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default = {
  tags: ['code-only'],
} satisfies Story;

```

The badge appears only in the toolbar, even if both component and story have the tag. Already tried to put the tag on component only, and story only. Storybook 8.4.3

![Screenshot 2024-11-14 alle 12 29 08](https://github.com/user-attachments/assets/21cf9208-55cb-404a-adba-baea75ca8146)

**Comment by dgteles** [comment]
Check in `main.ts` if you have another addons that manipulate the `sidebar`. If you have, remove them.

**Comment by Fedduh** [comment]
I also have for stories that include the meta with documentation (+ stories) but also include some manual .mdx files with code examples. I noticed that for these folders, the tags also don't show up.

(but maybe that's an odd setup I use..)

(for these 'groups' the icon is also a folder, instead of the component square icon)
![image](https://github.com/user-attachments/assets/85f342a1-4afd-4d42-a0d6-d085052c3428)

**Comment by Sidnioulz** [comment]
Hi @equinusocio, thanks for the report. Not all tags appear in the sidebar. What goes in the sidebar is controlled by the `display` option of your tagBadges config. So, if you didn't choose to set `display: true` (always displays, very verbose), or `display: ['component']` (displays only for component entries, but not for every story under them), you won't see badges.

Also, when a badge is displayed only for a component entry, the tag must actually be defined on the component (in the `meta`). Tags defined only on some stories do not bubble up to their component entry.

Could you please share your `tagBadges` config so I can see what's up?

**Comment by equinusocio** [comment]
Our `manager.ts` is pretty simple

```
import { addons } from '@storybook/manager-api';
import { themes } from '@storybook/theming';

import lualtekTheme from './lualtek-theme';

addons.setConfig({
  theme: { ...themes.dark, ...lualtekTheme },
  sidebar: {
    showRoots: true,
  },
});
```

We removed the addon since it doesn't work with a basic storybook boilerplate either.

**Comment by equinusocio** [comment]
Storybook 8.4.4, the repo is private, unfortunately, but we just setup their storybook `vite + ts + react` boilerplate

**Comment by equinusocio** [comment]
My repo is not public i can't share a link, but I can share my storybook config files:

preview.ts
```ts
import '@lualtek/themes/web';
import '../packages/react-components/src/core.css';
import './overrides.css';

import { withThemeByDataAttribute } from '@storybook/addon-themes';
import type { ReactRenderer } from '@storybook/react';
import { Preview } from '@storybook/react';
import { themes } from '@storybook/theming';

import lualtekTheme from './lualtek-theme';

const preview: Preview = {
  decorators: [
    withThemeByDataAttribute<ReactRenderer>({
      themes: {
        auto: 'auto',
        light: 'light',
        dark: 'dark',
      },
      defaultTheme: 'dark',
    }),
  ],
  parameters: {
    backgrounds: { disable: true },
    docs: {
      theme: { ...themes.dark, ...lualtekTheme },
    },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },
  },
};

export default preview;
```


manager.ts
```

import { addons } from '@storybook/manager-api';
import { themes } from '@storybook/theming';

import lualtekTheme from './lualtek-theme';

addons.setConfig({
  theme: { ...themes.dark, ...lualtekTheme },
  sidebar: {
    showRoots: true,
  },
});
```

main.ts
```
/* eslint-disable no-param-reassign */
import { dirname, join, resolve } from 'node:path';

import type { StorybookConfig } from '@storybook/react-vite';

/**
 * This function is used to resolve the absolute path of a package.
 * It is needed in projects that use Yarn PnP or are set up within a monorepo.
 */
function getAbsolutePath(value: string): string {
  return dirname(require.resolve(join(value, 'package.json')));
}

const config: StorybookConfig = {
  stories: ['../packages/**/src/**/*.stories.@(js|jsx|ts|tsx)'],
  addons: [
    getAbsolutePath('@storybook/addon-onboarding'),
    getAbsolutePath('@storybook/addon-links'),
    getAbsolutePath('@storybook/addon-essentials'),
    getAbsolutePath('@storybook/addon-interactions'),
    getAbsolutePath('@storybook/addon-themes'),
  ],
  framework: {
    name: getAbsolutePath('@storybook/react-vite'),
    options: {},
  },
  docs: {
    autodocs: true,
  },
  typescript: {
    check: false,
    reactDocgen: 'react-docgen-typescript',
    reactDocgenTypescriptOptions: {
      shouldExtractLiteralValuesFromEnum: true,
      propFilter: prop => (prop.parent ? !prop.parent.fileName.includes('node_modules') : true),
    },
  },
  viteFinal: async (config) => {
    if (config && config.resolve && config.resolve.alias) {
      config.resolve.alias['@/components'] = resolve(__dirname, '../packages/react-components/src');
      config.resolve.alias['@/charts'] = resolve(__dirname, '../packages/charts/src');
      return config;
    }

    return config;
  },
};
export default config;
```

**Comment by Sidnioulz** [comment]
@equinusocio try that instead?


```ts
// .storybook/manager.ts
import { addons } from '@storybook/manager-api';
import { themes } from '@storybook/theming';
import { renderLabel } from 'storybook-addon-tag-badges'

import lualtekTheme from './lualtek-theme';

addons.setConfig({
  theme: { ...themes.dark, ...lualtekTheme },
  sidebar: {
    renderLabel,
    showRoots: true,
  },
});
```

**Comment by equinusocio** [comment]
Yep that fixed the missing label, but `renderLabel` throws an eslint error
![Screenshot 2024-11-26 alle 10 21 17](https://github.com/user-attachments/assets/aca9c694-767a-4429-b0d2-6e1e2e15d7f0)

**Comment by Sidnioulz** [comment]
RE: the ESLint error, I don't have it locally (no unsafe assignment reported), so I'd love to see what the exact error message is, maybe alongside your tsconfig and eslint config?

----

This isn't a bug in this addon. It's a general limitation of `addons.setConfig`. When you override it in your manager, anything defined by addons will be overridden. To prevent that, you need to either do what you did by reading the previous config and merging the changes, or re-add `renderLabel`.

**Comment by equinusocio** [comment]
Ok thanks! Can you mention this in the doc/readme to avoid future similar issues?

**Comment by Sidnioulz** [comment]
Thanks for bringing this up @equinusocio. I did add README doc since you opened that issue, but I'll develop it further the next time the issue comes up.

**Comment by Sidnioulz** [comment]
There could be a bug in https://github.com/storybookjs/storybook/blob/next/code/core/src/manager-api/modules/layout.ts#L391 where addon-injected changes aren't part of the initial store state and some data gets erased through `setConfig`, which would explain why some things seem to merge, and others not.

I'll ask around.
