### ISSUE TITLE
Sidebar filters and sidebar tag badges don't co-exist

### ISSUE THREAD

**Issue by Sidnioulz** [Sidnioulz/storybook-addon-tag-badges#19]
#

I had the same issue. I noticed that when removing my sidebar filters in manager.ts, it did show up.

I have a sidebar filter in manager.ts so it won't display my stories with tag 'chromatic-only'

manager.ts
import { addons } from '@storybook/manager-api';

```typescript
addons.setConfig({
  sidebar: {
    filters: {
      patterns: (item) => {
        // in the sidebar exclude all items with the tag 'chromatic-only'
        return !item.tags?.includes('chromatic-only');
      },
    },
  },
});
```

_Originally posted by @Fedduh in https://github.com/Sidnioulz/storybook-addon-tag-badges/issues/15#issuecomment-2482298338_

**Comment by Sidnioulz** [comment]
Hi @Fedduh, sadly I could not reproduce this issue.

I've added the same sidebar filter config you're using on my local storybook instance on the `main` branch. Could you please run it and confirm you see the sidebar badges?

Could you please share a repo where sidebar filters trigger the issue so I can investigate it?

**Comment by Fedduh** [comment]
It was a bit of a hassle to setup a repo (my own repo is private).
I used some AI to set it up, but it does demostrate the issue. Perhaps it's cause by the Angular version of Storybook?

This is the stackblitz:
https://stackblitz.com/edit/sb1-kd55we?file=.storybook%2Fmanager.ts

If you run it (npm i && npm start) it will show the badge in the sidebar, and on top
![image](https://github.com/user-attachments/assets/792cc458-89db-4df0-a3c2-e6fe85a30099)


When you 
- comment out the code in './storybook/manager.ts' (the sidebar property)
- restart the application (stop current and npm start)

It will only show on top.
![image](https://github.com/user-attachments/assets/c4707238-e72e-4e6e-9bb8-b965425d99e2)


Hope this helps you debugging. I could indeed not reproduce the issue in your main branch.

**Comment by Sidnioulz** [comment]
I suspect that `addons.setConfig({ sidebar })` erases the _whole_ sidebar object, including `renderLabel`.

Could you try to keep your `filters` and add the following?

```ts
// .storybook/manager.ts
import { addons } from '@storybook/manager-api'
import { renderLabel } from 'storybook-addon-tag-badges'

const filters = { /* ... */ };

addons.setConfig({
  sidebar: {
    filters,
    renderLabel,
  }
})

**Comment by Fedduh** [comment]
That indeed fixes it! Thanks :)

**Comment by Sidnioulz** [comment]
Yay! Thanks for reporting back. I'll add a more explicit use case in the README so it's easier to spot.
