### ISSUE TITLE
Display badges in sidebar for top-level docs/story entries

### ISSUE THREAD

**Issue by RomainGaillard33** [Sidnioulz/storybook-addon-tag-badges#26]
Hello, 

My "spacings" documentation is deprecated, yet it doesn't show in the sidebar.
![{B634F951-E7D2-4598-86D7-4393043FD5E3}](https://github.com/user-attachments/assets/eae8546e-f3a2-455c-a334-f242836e9148)

However, the badge does appear correctly in the top bar.
![{F5B5E3B4-7A68-4180-8379-E67DB5F1B8D8}](https://github.com/user-attachments/assets/cfdf214c-d1af-4dcb-8eb8-f0cc4008ba17)

**Comment by Sidnioulz** [comment]
Thanks for the report @RomainGaillard33!

Could you clarify, for reproduction, is this a regular MDX file? Did you pass tags with the `tags` prop of `Meta`?

**Comment by Sidnioulz** [comment]
So, I know why this is happening. By default, I hide most sidebar badges on stories/docs, to prevent noise in the sidebar for stories and docs that are embedded in a component. I will rework the display options and the default display to instead show sidebar badges only on items of depth 0 and 1.

**Comment by RomainGaillard33** [comment]
Hi @Sidnioulz ,

I sorry for not see your questions earliere. I’ve just seen that you already addressed the issue, and I wanted to sincerely thank you for the fix!
