### ISSUE TITLE
Story-level badges are not displayed in sidebar by default

### ISSUE THREAD

**Issue by ajkl2533** [Sidnioulz/storybook-addon-tag-badges#27]
Hi there, nice job with this addon.

I'm not sure if I missed some configuration or if it's not supported, but I can't find a way how to display story-level badge in sidebar. I can see the badge in toolbar but placing it in sidebar makes it more visible.

<img width="916" alt="Screenshot 2024-11-22 at 18 31 33" src="https://github.com/user-attachments/assets/5d3c93ed-edb6-4c37-b454-e69413452159">

❓ I also have one more question related to story-level badges. Would it be somehow possible to expose badges next to story names in autodocs pages?

**Comment by Sidnioulz** [comment]
Hi @ajkl2533!

Thanks for the kind words. By default, most badges are hidden in the sidebar. If I showed them, this is what would happen for component-defined tags:

![image](https://github.com/user-attachments/assets/bc77b9e8-c79a-46ee-bc16-f5778989820a)

So, by default story/docs badges aren't shown. With the improvement coded for #26, they will soon be shown only if top-level, but not within an expander.

I'll see if I can fetch the parent's tags and display story/docs tags for children that aren't also displayed on the parent, but can't promise yet. Doing that may also decrease performance.

----

Regarding your second question, could you please make a separate issue to help me track it? I haven't thought about autodocs yet but I wanted to try and make a React component to display badges in MDX.

**Comment by Sidnioulz** [comment]
![image](https://github.com/user-attachments/assets/14089f9b-0f8a-420e-a1a8-165fd3ce3566)

It was feasible in the end. Will write doc, tests and release it soon.

**Comment by ajkl2533** [comment]
Thank you @Sidnioulz incredible speed 🙏 I created separate issue for the second question

**Comment by Sidnioulz** [comment]
Could you please confirm if your issue was fixed? :)

**Comment by ajkl2533** [comment]
Yes it works like a charm 👍
